### ISSUE TITLE
mechanical issues

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/ZHL_RF_AMP_3U#2]
Move the ZHL amplifier by 5mm - the SMA coupler doesn't fit
![signal-2022-03-14-094319_001](https://user-images.githubusercontent.com/4325054/158153391-667b0622-3398-4544-bde5-cde26b0240c1.jpeg)

**Comment by kaolpr** [comment]
Also holes in the front panel seem to be too low. In FP project distance between center of the RF OUT cutout and edge of the FP is 16.35 mm. Distance between edge of FP and component side of PCB is 4.07 mm. According to ZHL datasheet, distance between lower plane of the brick and RF connector center is 12.7 mm.

16.35 - 12.7 - 4.07 = -0.42 mm

![image](https://user-images.githubusercontent.com/9166701/158352856-85978cb4-1297-41cc-8a0f-0ecfa03c3721.png)

**Comment by kaolpr** [comment]
Heatsink that comes with ZHL is too high to fit in 8HP module.

**Comment by kaolpr** [comment]
Maybe we could avoid stiff connections? There is still space to move ZHL back so we could use ~5 cm SMA what would make project immune to misalignments.

**Comment by gkasprow** [comment]
the new revision will support various modules with different SMA connector height. Let's use short piece of SMA connector then.
