### ISSUE TITLE
Documentation for supported amp models

### ISSUE THREAD

**Issue by AVB25** [sinara-hw/ZHL_RF_AMP_3U#5]
Currently, the Wiki for the repo only specifies that each PCB can hold one ZHL 2010 amp. However, the design can be used without modification with a ZHL 3010 amp instead. As well as this, the latest release ([https://github.com/sinara-hw/ZHL_RF_AMP_3U/releases/tag/v2.0rc1](url)) includes a design that can power ZHL-1-2WX-S+ gain blocks for high RF power requirements. Should these be added to the wiki, or to a README?

**Comment by gkasprow** [comment]
added to wiki
